spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    open-in-view: false
  batch:
    job:
      name: "MYBATIS_CHUNK_JOB"
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
mybatis:
  mapper-locations: classpath:/xml_mybatis/customer.xml